// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core_functionality.proto

package org.spin.grpc.util;

public final class ADempiereCoreFunctionality {
  private ADempiereCoreFunctionality() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_GetCountryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_GetCountryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListLanguagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListLanguagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListLanguagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListLanguagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Country_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Country_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Currency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Currency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Organization_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Organization_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListOrganizationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListOrganizationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListOrganizationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListOrganizationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Warehouse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Warehouse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListWarehousesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListWarehousesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ListWarehousesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ListWarehousesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_UnitOfMeasure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_UnitOfMeasure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Charge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Charge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_BusinessPartner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_BusinessPartner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_DocumentType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_DocumentType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_SalesRepresentative_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_SalesRepresentative_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_TaxRate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_TaxRate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ProductPrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ProductPrice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Language_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Language_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030core_functionality.proto\022\004data\032\024base_d" +
      "ata_type.proto\"g\n\rClientRequest\022\023\n\013sessi" +
      "onUuid\030\001 \001(\t\022\020\n\010language\030\002 \001(\t\022\030\n\020organi" +
      "zationUuid\030\003 \001(\t\022\025\n\rwarehouseUuid\030\004 \001(\t\"" +
      "g\n\021GetCountryRequest\022\023\n\013countryUuid\030\001 \001(" +
      "\t\022\021\n\tcountryId\030\002 \001(\005\022*\n\rclientRequest\030\003 " +
      "\001(\0132\023.data.ClientRequest\"i\n\024ListLanguage" +
      "sRequest\022*\n\rclientRequest\030\001 \001(\0132\023.data.C" +
      "lientRequest\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_" +
      "token\030\003 \001(\t\"h\n\025ListLanguagesResponse\022\023\n\013",
      "recordCount\030\001 \001(\003\022!\n\tlanguages\030\002 \003(\0132\016.d" +
      "ata.Language\022\027\n\017next_page_token\030\003 \001(\t\"\237\004" +
      "\n\007Country\022\014\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\023\n\013c" +
      "ountryCode\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\023\n\013descri" +
      "ption\030\005 \001(\t\022\021\n\thasRegion\030\006 \001(\010\022\022\n\nregion" +
      "Name\030\007 \001(\t\022\027\n\017displaySequence\030\010 \001(\t\022\035\n\025i" +
      "sAddressLinesReverse\030\t \001(\010\022\027\n\017captureSeq" +
      "uence\030\n \001(\t\022\034\n\024displaySequenceLocal\030\013 \001(" +
      "\t\022\"\n\032isAddressLinesLocalReverse\030\014 \001(\010\022\030\n" +
      "\020expressionPostal\030\r \001(\t\022\024\n\014hasPostalAdd\030",
      "\016 \001(\010\022\027\n\017expressionPhone\030\017 \001(\t\022\021\n\tmediaS" +
      "ize\030\020 \001(\t\022\037\n\027expressionBankRoutingNo\030\021 \001" +
      "(\t\022\037\n\027expressionBankAccountNo\030\022 \001(\t\022\020\n\010l" +
      "anguage\030\023 \001(\t\022\034\n\024allowCitiesOutOfList\030\024 " +
      "\001(\010\022\030\n\020isPostcodeLookup\030\025 \001(\010\022 \n\010currenc" +
      "y\030\026 \001(\0132\016.data.Currency\"\215\001\n\010Currency\022\014\n\004" +
      "uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\017\n\007iSOCode\030\003 \001(\t\022" +
      "\021\n\tcurSymbol\030\004 \001(\t\022\023\n\013description\030\005 \001(\t\022" +
      "\024\n\014stdPrecision\030\006 \001(\005\022\030\n\020costingPrecisio" +
      "n\030\007 \001(\005\"\250\001\n\014Organization\022\014\n\004uuid\030\001 \001(\t\022\n",
      "\n\002id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\023\n\013description\030" +
      "\004 \001(\t\022\022\n\nisReadOnly\030\005 \001(\010\022\014\n\004duns\030\006 \001(\t\022" +
      "\r\n\005taxId\030\007 \001(\t\022\r\n\005phone\030\010 \001(\t\022\016\n\006phone2\030" +
      "\t \001(\t\022\013\n\003fax\030\n \001(\t\"t\n\031ListOrganizationsR" +
      "esponse\022\023\n\013recordCount\030\001 \001(\003\022)\n\rorganiza" +
      "tions\030\002 \003(\0132\022.data.Organization\022\027\n\017next_" +
      "page_token\030\004 \001(\t\"\217\001\n\030ListOrganizationsRe" +
      "quest\022*\n\rclientRequest\030\001 \001(\0132\023.data.Clie" +
      "ntRequest\022\016\n\006roleId\030\002 \001(\005\022\020\n\010roleUuid\030\003 " +
      "\001(\t\022\021\n\tpage_size\030\004 \001(\005\022\022\n\npage_token\030\005 \001",
      "(\t\"H\n\tWarehouse\022\014\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(" +
      "\005\022\014\n\004name\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"k\n\026" +
      "ListWarehousesResponse\022\023\n\013recordCount\030\001 " +
      "\001(\003\022#\n\nwarehouses\030\002 \003(\0132\017.data.Warehouse" +
      "\022\027\n\017next_page_token\030\004 \001(\t\"\234\001\n\025ListWareho" +
      "usesRequest\022*\n\rclientRequest\030\001 \001(\0132\023.dat" +
      "a.ClientRequest\022\026\n\016organizationId\030\002 \001(\005\022" +
      "\030\n\020organizationUuid\030\003 \001(\t\022\021\n\tpage_size\030\004" +
      " \001(\005\022\022\n\npage_token\030\005 \001(\t\"\232\001\n\rUnitOfMeasu" +
      "re\022\014\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004code\030\003 \001",
      "(\t\022\016\n\006symbol\030\004 \001(\t\022\014\n\004name\030\005 \001(\t\022\023\n\013desc" +
      "ription\030\006 \001(\t\022\024\n\014stdPrecision\030\007 \001(\005\022\030\n\020c" +
      "ostingPrecision\030\010 \001(\005\"E\n\006Charge\022\014\n\004uuid\030" +
      "\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\023\n\013descr" +
      "iption\030\004 \001(\t\"\233\001\n\017BusinessPartner\022\014\n\004uuid" +
      "\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005value\030\003 \001(\t\022\r\n\005tax" +
      "Id\030\004 \001(\t\022\014\n\004duns\030\005 \001(\t\022\r\n\005naics\030\006 \001(\t\022\014\n" +
      "\004name\030\007 \001(\t\022\020\n\010lastName\030\010 \001(\t\022\023\n\013descrip" +
      "tion\030\t \001(\t\"^\n\014DocumentType\022\014\n\004uuid\030\001 \001(\t" +
      "\022\n\n\002id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\021\n\tprintName\030",
      "\004 \001(\t\022\023\n\013description\030\005 \001(\t\"R\n\023SalesRepre" +
      "sentative\022\014\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004n" +
      "ame\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"\251\005\n\007Produ" +
      "ct\022\014\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005value\030\003 " +
      "\001(\t\022\014\n\004name\030\004 \001(\t\022\014\n\004help\030\005 \001(\t\022\024\n\014docum" +
      "entNote\030\006 \001(\t\022\017\n\007uomName\030\007 \001(\t\022\023\n\013produc" +
      "tType\030\010 \001(\t\022\021\n\tisStocked\030\t \001(\010\022\022\n\nisDrop" +
      "Ship\030\n \001(\010\022\023\n\013isPurchased\030\013 \001(\010\022\016\n\006isSol" +
      "d\030\014 \001(\010\022\020\n\010imageURL\030\r \001(\t\022\033\n\023productCate" +
      "goryName\030\016 \001(\t\022\030\n\020productGroupName\030\017 \001(\t",
      "\022\030\n\020productClassName\030\020 \001(\t\022!\n\031productCla" +
      "ssificationName\030\021 \001(\t\022\035\n\006weight\030\022 \001(\0132\r." +
      "data.Decimal\022\035\n\006volume\030\023 \001(\0132\r.data.Deci" +
      "mal\022\013\n\003upc\030\024 \001(\t\022\013\n\003sku\030\025 \001(\t\022\022\n\nshelfWi" +
      "dth\030\026 \001(\005\022\"\n\013shelfHeight\030\027 \001(\0132\r.data.De" +
      "cimal\022\022\n\nshelfDepth\030\030 \001(\005\022\024\n\014unitsPerPac" +
      "k\030\031 \001(\005\022%\n\016unitsPerPallet\030\032 \001(\0132\r.data.D" +
      "ecimal\022\025\n\rguaranteeDays\030\033 \001(\005\022\026\n\016descrip" +
      "tionURL\030\034 \001(\t\022\021\n\tversionNo\030\035 \001(\t\022\023\n\013taxC" +
      "ategory\030\036 \001(\t\022\023\n\013description\030\037 \001(\t\"y\n\007Ta",
      "xRate\022\014\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004name\030" +
      "\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\024\n\014taxIndicat" +
      "or\030\005 \001(\t\022\033\n\004rate\030\006 \001(\0132\r.data.Decimal\"\321\003" +
      "\n\014ProductPrice\022\036\n\007product\030\001 \001(\0132\r.data.P" +
      "roduct\022 \n\tpriceList\030\002 \001(\0132\r.data.Decimal" +
      "\022\037\n\010priceStd\030\003 \001(\0132\r.data.Decimal\022!\n\npri" +
      "ceLimit\030\004 \001(\0132\r.data.Decimal\022\025\n\rpriceLis" +
      "tName\030\005 \001(\t\022\025\n\risTaxIncluded\030\006 \001(\010\022\021\n\tva" +
      "lidFrom\030\007 \001(\003\022 \n\010currency\030\010 \001(\0132\016.data.C" +
      "urrency\022\036\n\007taxRate\030\t \001(\0132\r.data.TaxRate\022",
      "\026\n\016pricePrecision\030\n \001(\005\022%\n\016quantityOnHan" +
      "d\030\013 \001(\0132\r.data.Decimal\022\'\n\020quantityReserv" +
      "ed\030\014 \001(\0132\r.data.Decimal\022&\n\017quantityOrder" +
      "ed\030\r \001(\0132\r.data.Decimal\022(\n\021quantityAvail" +
      "able\030\016 \001(\0132\r.data.Decimal\"\320\001\n\010Language\022\020" +
      "\n\010language\030\001 \001(\t\022\024\n\014languageName\030\002 \001(\t\022\023" +
      "\n\013languageISO\030\003 \001(\t\022\023\n\013countryCode\030\004 \001(\t" +
      "\022\026\n\016isBaseLanguage\030\005 \001(\010\022\030\n\020isSystemLang" +
      "uage\030\006 \001(\010\022\026\n\016isDecimalPoint\030\007 \001(\010\022\023\n\013da" +
      "tePattern\030\010 \001(\t\022\023\n\013timePattern\030\t \001(\t2\276\002\n",
      "\021CoreFunctionality\0226\n\nGetCountry\022\027.data." +
      "GetCountryRequest\032\r.data.Country\"\000\022V\n\021Li" +
      "stOrganizations\022\036.data.ListOrganizations" +
      "Request\032\037.data.ListOrganizationsResponse" +
      "\"\000\022M\n\016ListWarehouses\022\033.data.ListWarehous" +
      "esRequest\032\034.data.ListWarehousesResponse\"" +
      "\000\022J\n\rListLanguages\022\032.data.ListLanguagesR" +
      "equest\032\033.data.ListLanguagesResponse\"\000B8\n" +
      "\022org.spin.grpc.utilB\032ADempiereCoreFuncti" +
      "onalityP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.spin.grpc.util.ADempiereBase.getDescriptor(),
        }, assigner);
    internal_static_data_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ClientRequest_descriptor,
        new java.lang.String[] { "SessionUuid", "Language", "OrganizationUuid", "WarehouseUuid", });
    internal_static_data_GetCountryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_GetCountryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_GetCountryRequest_descriptor,
        new java.lang.String[] { "CountryUuid", "CountryId", "ClientRequest", });
    internal_static_data_ListLanguagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_data_ListLanguagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListLanguagesRequest_descriptor,
        new java.lang.String[] { "ClientRequest", "PageSize", "PageToken", });
    internal_static_data_ListLanguagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_data_ListLanguagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListLanguagesResponse_descriptor,
        new java.lang.String[] { "RecordCount", "Languages", "NextPageToken", });
    internal_static_data_Country_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_data_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Country_descriptor,
        new java.lang.String[] { "Uuid", "Id", "CountryCode", "Name", "Description", "HasRegion", "RegionName", "DisplaySequence", "IsAddressLinesReverse", "CaptureSequence", "DisplaySequenceLocal", "IsAddressLinesLocalReverse", "ExpressionPostal", "HasPostalAdd", "ExpressionPhone", "MediaSize", "ExpressionBankRoutingNo", "ExpressionBankAccountNo", "Language", "AllowCitiesOutOfList", "IsPostcodeLookup", "Currency", });
    internal_static_data_Currency_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_data_Currency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Currency_descriptor,
        new java.lang.String[] { "Uuid", "Id", "ISOCode", "CurSymbol", "Description", "StdPrecision", "CostingPrecision", });
    internal_static_data_Organization_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_data_Organization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Organization_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Name", "Description", "IsReadOnly", "Duns", "TaxId", "Phone", "Phone2", "Fax", });
    internal_static_data_ListOrganizationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_data_ListOrganizationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListOrganizationsResponse_descriptor,
        new java.lang.String[] { "RecordCount", "Organizations", "NextPageToken", });
    internal_static_data_ListOrganizationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_data_ListOrganizationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListOrganizationsRequest_descriptor,
        new java.lang.String[] { "ClientRequest", "RoleId", "RoleUuid", "PageSize", "PageToken", });
    internal_static_data_Warehouse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_data_Warehouse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Warehouse_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Name", "Description", });
    internal_static_data_ListWarehousesResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_data_ListWarehousesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListWarehousesResponse_descriptor,
        new java.lang.String[] { "RecordCount", "Warehouses", "NextPageToken", });
    internal_static_data_ListWarehousesRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_data_ListWarehousesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ListWarehousesRequest_descriptor,
        new java.lang.String[] { "ClientRequest", "OrganizationId", "OrganizationUuid", "PageSize", "PageToken", });
    internal_static_data_UnitOfMeasure_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_data_UnitOfMeasure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_UnitOfMeasure_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Code", "Symbol", "Name", "Description", "StdPrecision", "CostingPrecision", });
    internal_static_data_Charge_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_data_Charge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Charge_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Name", "Description", });
    internal_static_data_BusinessPartner_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_data_BusinessPartner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_BusinessPartner_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Value", "TaxId", "Duns", "Naics", "Name", "LastName", "Description", });
    internal_static_data_DocumentType_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_data_DocumentType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_DocumentType_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Name", "PrintName", "Description", });
    internal_static_data_SalesRepresentative_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_data_SalesRepresentative_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_SalesRepresentative_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Name", "Description", });
    internal_static_data_Product_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_data_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Product_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Value", "Name", "Help", "DocumentNote", "UomName", "ProductType", "IsStocked", "IsDropShip", "IsPurchased", "IsSold", "ImageURL", "ProductCategoryName", "ProductGroupName", "ProductClassName", "ProductClassificationName", "Weight", "Volume", "Upc", "Sku", "ShelfWidth", "ShelfHeight", "ShelfDepth", "UnitsPerPack", "UnitsPerPallet", "GuaranteeDays", "DescriptionURL", "VersionNo", "TaxCategory", "Description", });
    internal_static_data_TaxRate_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_data_TaxRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_TaxRate_descriptor,
        new java.lang.String[] { "Uuid", "Id", "Name", "Description", "TaxIndicator", "Rate", });
    internal_static_data_ProductPrice_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_data_ProductPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ProductPrice_descriptor,
        new java.lang.String[] { "Product", "PriceList", "PriceStd", "PriceLimit", "PriceListName", "IsTaxIncluded", "ValidFrom", "Currency", "TaxRate", "PricePrecision", "QuantityOnHand", "QuantityReserved", "QuantityOrdered", "QuantityAvailable", });
    internal_static_data_Language_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_data_Language_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Language_descriptor,
        new java.lang.String[] { "Language", "LanguageName", "LanguageISO", "CountryCode", "IsBaseLanguage", "IsSystemLanguage", "IsDecimalPoint", "DatePattern", "TimePattern", });
    org.spin.grpc.util.ADempiereBase.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
