// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package org.spin.grpc.util;

/**
 * <pre>
 * Record Chat
 * </pre>
 *
 * Protobuf type {@code data.ChatEntry}
 */
public  final class ChatEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ChatEntry)
    ChatEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatEntry.newBuilder() to construct.
  private ChatEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatEntry() {
    chatUuid_ = "";
    chatEntryUuid_ = "";
    subject_ = "";
    characterData_ = "";
    userUuid_ = "";
    userName_ = "";
    chatEntryType_ = 0;
    confidentialType_ = 0;
    moderatorStatus_ = 0;
    logDate_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            chatUuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            chatEntryUuid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            subject_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            characterData_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            userUuid_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            chatEntryType_ = rawValue;
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            confidentialType_ = rawValue;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            moderatorStatus_ = rawValue;
            break;
          }
          case 80: {

            logDate_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.spin.grpc.util.ADempiereData.internal_static_data_ChatEntry_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.spin.grpc.util.ADempiereData.internal_static_data_ChatEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.spin.grpc.util.ChatEntry.class, org.spin.grpc.util.ChatEntry.Builder.class);
  }

  /**
   * Protobuf enum {@code data.ChatEntry.ConfidentialType}
   */
  public enum ConfidentialType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PUBLIC = 0;</code>
     */
    PUBLIC(0),
    /**
     * <code>PARTER = 1;</code>
     */
    PARTER(1),
    /**
     * <code>INTERNAL = 2;</code>
     */
    INTERNAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PUBLIC = 0;</code>
     */
    public static final int PUBLIC_VALUE = 0;
    /**
     * <code>PARTER = 1;</code>
     */
    public static final int PARTER_VALUE = 1;
    /**
     * <code>INTERNAL = 2;</code>
     */
    public static final int INTERNAL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConfidentialType valueOf(int value) {
      return forNumber(value);
    }

    public static ConfidentialType forNumber(int value) {
      switch (value) {
        case 0: return PUBLIC;
        case 1: return PARTER;
        case 2: return INTERNAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConfidentialType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConfidentialType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConfidentialType>() {
            public ConfidentialType findValueByNumber(int number) {
              return ConfidentialType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.spin.grpc.util.ChatEntry.getDescriptor().getEnumTypes().get(0);
    }

    private static final ConfidentialType[] VALUES = values();

    public static ConfidentialType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConfidentialType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:data.ChatEntry.ConfidentialType)
  }

  /**
   * Protobuf enum {@code data.ChatEntry.ModeratorStatus}
   */
  public enum ModeratorStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOT_DISPLAYED = 0;</code>
     */
    NOT_DISPLAYED(0),
    /**
     * <code>PUBLISHED = 1;</code>
     */
    PUBLISHED(1),
    /**
     * <code>SUSPICIUS = 2;</code>
     */
    SUSPICIUS(2),
    /**
     * <code>TO_BE_REVIEWED = 3;</code>
     */
    TO_BE_REVIEWED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOT_DISPLAYED = 0;</code>
     */
    public static final int NOT_DISPLAYED_VALUE = 0;
    /**
     * <code>PUBLISHED = 1;</code>
     */
    public static final int PUBLISHED_VALUE = 1;
    /**
     * <code>SUSPICIUS = 2;</code>
     */
    public static final int SUSPICIUS_VALUE = 2;
    /**
     * <code>TO_BE_REVIEWED = 3;</code>
     */
    public static final int TO_BE_REVIEWED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ModeratorStatus valueOf(int value) {
      return forNumber(value);
    }

    public static ModeratorStatus forNumber(int value) {
      switch (value) {
        case 0: return NOT_DISPLAYED;
        case 1: return PUBLISHED;
        case 2: return SUSPICIUS;
        case 3: return TO_BE_REVIEWED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ModeratorStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ModeratorStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModeratorStatus>() {
            public ModeratorStatus findValueByNumber(int number) {
              return ModeratorStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.spin.grpc.util.ChatEntry.getDescriptor().getEnumTypes().get(1);
    }

    private static final ModeratorStatus[] VALUES = values();

    public static ModeratorStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ModeratorStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:data.ChatEntry.ModeratorStatus)
  }

  /**
   * Protobuf enum {@code data.ChatEntry.ChatEntryType}
   */
  public enum ChatEntryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOTE_FLAT = 0;</code>
     */
    NOTE_FLAT(0),
    /**
     * <code>FORUM_THREADED = 1;</code>
     */
    FORUM_THREADED(1),
    /**
     * <code>WIKI = 2;</code>
     */
    WIKI(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOTE_FLAT = 0;</code>
     */
    public static final int NOTE_FLAT_VALUE = 0;
    /**
     * <code>FORUM_THREADED = 1;</code>
     */
    public static final int FORUM_THREADED_VALUE = 1;
    /**
     * <code>WIKI = 2;</code>
     */
    public static final int WIKI_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChatEntryType valueOf(int value) {
      return forNumber(value);
    }

    public static ChatEntryType forNumber(int value) {
      switch (value) {
        case 0: return NOTE_FLAT;
        case 1: return FORUM_THREADED;
        case 2: return WIKI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatEntryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatEntryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatEntryType>() {
            public ChatEntryType findValueByNumber(int number) {
              return ChatEntryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.spin.grpc.util.ChatEntry.getDescriptor().getEnumTypes().get(2);
    }

    private static final ChatEntryType[] VALUES = values();

    public static ChatEntryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatEntryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:data.ChatEntry.ChatEntryType)
  }

  public static final int CHATUUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object chatUuid_;
  /**
   * <code>string chatUuid = 1;</code>
   */
  public java.lang.String getChatUuid() {
    java.lang.Object ref = chatUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string chatUuid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getChatUuidBytes() {
    java.lang.Object ref = chatUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHATENTRYUUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object chatEntryUuid_;
  /**
   * <code>string chatEntryUuid = 2;</code>
   */
  public java.lang.String getChatEntryUuid() {
    java.lang.Object ref = chatEntryUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatEntryUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string chatEntryUuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getChatEntryUuidBytes() {
    java.lang.Object ref = chatEntryUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatEntryUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_FIELD_NUMBER = 3;
  private volatile java.lang.Object subject_;
  /**
   * <code>string subject = 3;</code>
   */
  public java.lang.String getSubject() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }
  /**
   * <code>string subject = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHARACTERDATA_FIELD_NUMBER = 4;
  private volatile java.lang.Object characterData_;
  /**
   * <code>string characterData = 4;</code>
   */
  public java.lang.String getCharacterData() {
    java.lang.Object ref = characterData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      characterData_ = s;
      return s;
    }
  }
  /**
   * <code>string characterData = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCharacterDataBytes() {
    java.lang.Object ref = characterData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      characterData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERUUID_FIELD_NUMBER = 5;
  private volatile java.lang.Object userUuid_;
  /**
   * <code>string userUuid = 5;</code>
   */
  public java.lang.String getUserUuid() {
    java.lang.Object ref = userUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string userUuid = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUserUuidBytes() {
    java.lang.Object ref = userUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 6;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHATENTRYTYPE_FIELD_NUMBER = 7;
  private int chatEntryType_;
  /**
   * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
   */
  public int getChatEntryTypeValue() {
    return chatEntryType_;
  }
  /**
   * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
   */
  public org.spin.grpc.util.ChatEntry.ChatEntryType getChatEntryType() {
    org.spin.grpc.util.ChatEntry.ChatEntryType result = org.spin.grpc.util.ChatEntry.ChatEntryType.valueOf(chatEntryType_);
    return result == null ? org.spin.grpc.util.ChatEntry.ChatEntryType.UNRECOGNIZED : result;
  }

  public static final int CONFIDENTIALTYPE_FIELD_NUMBER = 8;
  private int confidentialType_;
  /**
   * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
   */
  public int getConfidentialTypeValue() {
    return confidentialType_;
  }
  /**
   * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
   */
  public org.spin.grpc.util.ChatEntry.ConfidentialType getConfidentialType() {
    org.spin.grpc.util.ChatEntry.ConfidentialType result = org.spin.grpc.util.ChatEntry.ConfidentialType.valueOf(confidentialType_);
    return result == null ? org.spin.grpc.util.ChatEntry.ConfidentialType.UNRECOGNIZED : result;
  }

  public static final int MODERATORSTATUS_FIELD_NUMBER = 9;
  private int moderatorStatus_;
  /**
   * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
   */
  public int getModeratorStatusValue() {
    return moderatorStatus_;
  }
  /**
   * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
   */
  public org.spin.grpc.util.ChatEntry.ModeratorStatus getModeratorStatus() {
    org.spin.grpc.util.ChatEntry.ModeratorStatus result = org.spin.grpc.util.ChatEntry.ModeratorStatus.valueOf(moderatorStatus_);
    return result == null ? org.spin.grpc.util.ChatEntry.ModeratorStatus.UNRECOGNIZED : result;
  }

  public static final int LOGDATE_FIELD_NUMBER = 10;
  private long logDate_;
  /**
   * <code>int64 logDate = 10;</code>
   */
  public long getLogDate() {
    return logDate_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getChatUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chatUuid_);
    }
    if (!getChatEntryUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chatEntryUuid_);
    }
    if (!getSubjectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subject_);
    }
    if (!getCharacterDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, characterData_);
    }
    if (!getUserUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userUuid_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userName_);
    }
    if (chatEntryType_ != org.spin.grpc.util.ChatEntry.ChatEntryType.NOTE_FLAT.getNumber()) {
      output.writeEnum(7, chatEntryType_);
    }
    if (confidentialType_ != org.spin.grpc.util.ChatEntry.ConfidentialType.PUBLIC.getNumber()) {
      output.writeEnum(8, confidentialType_);
    }
    if (moderatorStatus_ != org.spin.grpc.util.ChatEntry.ModeratorStatus.NOT_DISPLAYED.getNumber()) {
      output.writeEnum(9, moderatorStatus_);
    }
    if (logDate_ != 0L) {
      output.writeInt64(10, logDate_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getChatUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chatUuid_);
    }
    if (!getChatEntryUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chatEntryUuid_);
    }
    if (!getSubjectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subject_);
    }
    if (!getCharacterDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, characterData_);
    }
    if (!getUserUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userUuid_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userName_);
    }
    if (chatEntryType_ != org.spin.grpc.util.ChatEntry.ChatEntryType.NOTE_FLAT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, chatEntryType_);
    }
    if (confidentialType_ != org.spin.grpc.util.ChatEntry.ConfidentialType.PUBLIC.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, confidentialType_);
    }
    if (moderatorStatus_ != org.spin.grpc.util.ChatEntry.ModeratorStatus.NOT_DISPLAYED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, moderatorStatus_);
    }
    if (logDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, logDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.spin.grpc.util.ChatEntry)) {
      return super.equals(obj);
    }
    org.spin.grpc.util.ChatEntry other = (org.spin.grpc.util.ChatEntry) obj;

    boolean result = true;
    result = result && getChatUuid()
        .equals(other.getChatUuid());
    result = result && getChatEntryUuid()
        .equals(other.getChatEntryUuid());
    result = result && getSubject()
        .equals(other.getSubject());
    result = result && getCharacterData()
        .equals(other.getCharacterData());
    result = result && getUserUuid()
        .equals(other.getUserUuid());
    result = result && getUserName()
        .equals(other.getUserName());
    result = result && chatEntryType_ == other.chatEntryType_;
    result = result && confidentialType_ == other.confidentialType_;
    result = result && moderatorStatus_ == other.moderatorStatus_;
    result = result && (getLogDate()
        == other.getLogDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHATUUID_FIELD_NUMBER;
    hash = (53 * hash) + getChatUuid().hashCode();
    hash = (37 * hash) + CHATENTRYUUID_FIELD_NUMBER;
    hash = (53 * hash) + getChatEntryUuid().hashCode();
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getSubject().hashCode();
    hash = (37 * hash) + CHARACTERDATA_FIELD_NUMBER;
    hash = (53 * hash) + getCharacterData().hashCode();
    hash = (37 * hash) + USERUUID_FIELD_NUMBER;
    hash = (53 * hash) + getUserUuid().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + CHATENTRYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + chatEntryType_;
    hash = (37 * hash) + CONFIDENTIALTYPE_FIELD_NUMBER;
    hash = (53 * hash) + confidentialType_;
    hash = (37 * hash) + MODERATORSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + moderatorStatus_;
    hash = (37 * hash) + LOGDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLogDate());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.spin.grpc.util.ChatEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.spin.grpc.util.ChatEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ChatEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ChatEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.spin.grpc.util.ChatEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Record Chat
   * </pre>
   *
   * Protobuf type {@code data.ChatEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ChatEntry)
      org.spin.grpc.util.ChatEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.spin.grpc.util.ADempiereData.internal_static_data_ChatEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.spin.grpc.util.ADempiereData.internal_static_data_ChatEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.spin.grpc.util.ChatEntry.class, org.spin.grpc.util.ChatEntry.Builder.class);
    }

    // Construct using org.spin.grpc.util.ChatEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      chatUuid_ = "";

      chatEntryUuid_ = "";

      subject_ = "";

      characterData_ = "";

      userUuid_ = "";

      userName_ = "";

      chatEntryType_ = 0;

      confidentialType_ = 0;

      moderatorStatus_ = 0;

      logDate_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.spin.grpc.util.ADempiereData.internal_static_data_ChatEntry_descriptor;
    }

    public org.spin.grpc.util.ChatEntry getDefaultInstanceForType() {
      return org.spin.grpc.util.ChatEntry.getDefaultInstance();
    }

    public org.spin.grpc.util.ChatEntry build() {
      org.spin.grpc.util.ChatEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.spin.grpc.util.ChatEntry buildPartial() {
      org.spin.grpc.util.ChatEntry result = new org.spin.grpc.util.ChatEntry(this);
      result.chatUuid_ = chatUuid_;
      result.chatEntryUuid_ = chatEntryUuid_;
      result.subject_ = subject_;
      result.characterData_ = characterData_;
      result.userUuid_ = userUuid_;
      result.userName_ = userName_;
      result.chatEntryType_ = chatEntryType_;
      result.confidentialType_ = confidentialType_;
      result.moderatorStatus_ = moderatorStatus_;
      result.logDate_ = logDate_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.spin.grpc.util.ChatEntry) {
        return mergeFrom((org.spin.grpc.util.ChatEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.spin.grpc.util.ChatEntry other) {
      if (other == org.spin.grpc.util.ChatEntry.getDefaultInstance()) return this;
      if (!other.getChatUuid().isEmpty()) {
        chatUuid_ = other.chatUuid_;
        onChanged();
      }
      if (!other.getChatEntryUuid().isEmpty()) {
        chatEntryUuid_ = other.chatEntryUuid_;
        onChanged();
      }
      if (!other.getSubject().isEmpty()) {
        subject_ = other.subject_;
        onChanged();
      }
      if (!other.getCharacterData().isEmpty()) {
        characterData_ = other.characterData_;
        onChanged();
      }
      if (!other.getUserUuid().isEmpty()) {
        userUuid_ = other.userUuid_;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (other.chatEntryType_ != 0) {
        setChatEntryTypeValue(other.getChatEntryTypeValue());
      }
      if (other.confidentialType_ != 0) {
        setConfidentialTypeValue(other.getConfidentialTypeValue());
      }
      if (other.moderatorStatus_ != 0) {
        setModeratorStatusValue(other.getModeratorStatusValue());
      }
      if (other.getLogDate() != 0L) {
        setLogDate(other.getLogDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.spin.grpc.util.ChatEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.spin.grpc.util.ChatEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object chatUuid_ = "";
    /**
     * <code>string chatUuid = 1;</code>
     */
    public java.lang.String getChatUuid() {
      java.lang.Object ref = chatUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chatUuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChatUuidBytes() {
      java.lang.Object ref = chatUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chatUuid = 1;</code>
     */
    public Builder setChatUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chatUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chatUuid = 1;</code>
     */
    public Builder clearChatUuid() {
      
      chatUuid_ = getDefaultInstance().getChatUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string chatUuid = 1;</code>
     */
    public Builder setChatUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chatUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chatEntryUuid_ = "";
    /**
     * <code>string chatEntryUuid = 2;</code>
     */
    public java.lang.String getChatEntryUuid() {
      java.lang.Object ref = chatEntryUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatEntryUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chatEntryUuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getChatEntryUuidBytes() {
      java.lang.Object ref = chatEntryUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatEntryUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chatEntryUuid = 2;</code>
     */
    public Builder setChatEntryUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chatEntryUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chatEntryUuid = 2;</code>
     */
    public Builder clearChatEntryUuid() {
      
      chatEntryUuid_ = getDefaultInstance().getChatEntryUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string chatEntryUuid = 2;</code>
     */
    public Builder setChatEntryUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chatEntryUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subject_ = "";
    /**
     * <code>string subject = 3;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject = 3;</code>
     */
    public Builder setSubject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subject_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 3;</code>
     */
    public Builder clearSubject() {
      
      subject_ = getDefaultInstance().getSubject();
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 3;</code>
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subject_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object characterData_ = "";
    /**
     * <code>string characterData = 4;</code>
     */
    public java.lang.String getCharacterData() {
      java.lang.Object ref = characterData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        characterData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string characterData = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCharacterDataBytes() {
      java.lang.Object ref = characterData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        characterData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string characterData = 4;</code>
     */
    public Builder setCharacterData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      characterData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string characterData = 4;</code>
     */
    public Builder clearCharacterData() {
      
      characterData_ = getDefaultInstance().getCharacterData();
      onChanged();
      return this;
    }
    /**
     * <code>string characterData = 4;</code>
     */
    public Builder setCharacterDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      characterData_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userUuid_ = "";
    /**
     * <code>string userUuid = 5;</code>
     */
    public java.lang.String getUserUuid() {
      java.lang.Object ref = userUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userUuid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserUuidBytes() {
      java.lang.Object ref = userUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userUuid = 5;</code>
     */
    public Builder setUserUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userUuid = 5;</code>
     */
    public Builder clearUserUuid() {
      
      userUuid_ = getDefaultInstance().getUserUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string userUuid = 5;</code>
     */
    public Builder setUserUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 6;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 6;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 6;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 6;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private int chatEntryType_ = 0;
    /**
     * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
     */
    public int getChatEntryTypeValue() {
      return chatEntryType_;
    }
    /**
     * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
     */
    public Builder setChatEntryTypeValue(int value) {
      chatEntryType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
     */
    public org.spin.grpc.util.ChatEntry.ChatEntryType getChatEntryType() {
      org.spin.grpc.util.ChatEntry.ChatEntryType result = org.spin.grpc.util.ChatEntry.ChatEntryType.valueOf(chatEntryType_);
      return result == null ? org.spin.grpc.util.ChatEntry.ChatEntryType.UNRECOGNIZED : result;
    }
    /**
     * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
     */
    public Builder setChatEntryType(org.spin.grpc.util.ChatEntry.ChatEntryType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      chatEntryType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.data.ChatEntry.ChatEntryType chatEntryType = 7;</code>
     */
    public Builder clearChatEntryType() {
      
      chatEntryType_ = 0;
      onChanged();
      return this;
    }

    private int confidentialType_ = 0;
    /**
     * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
     */
    public int getConfidentialTypeValue() {
      return confidentialType_;
    }
    /**
     * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
     */
    public Builder setConfidentialTypeValue(int value) {
      confidentialType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
     */
    public org.spin.grpc.util.ChatEntry.ConfidentialType getConfidentialType() {
      org.spin.grpc.util.ChatEntry.ConfidentialType result = org.spin.grpc.util.ChatEntry.ConfidentialType.valueOf(confidentialType_);
      return result == null ? org.spin.grpc.util.ChatEntry.ConfidentialType.UNRECOGNIZED : result;
    }
    /**
     * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
     */
    public Builder setConfidentialType(org.spin.grpc.util.ChatEntry.ConfidentialType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      confidentialType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.data.ChatEntry.ConfidentialType confidentialType = 8;</code>
     */
    public Builder clearConfidentialType() {
      
      confidentialType_ = 0;
      onChanged();
      return this;
    }

    private int moderatorStatus_ = 0;
    /**
     * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
     */
    public int getModeratorStatusValue() {
      return moderatorStatus_;
    }
    /**
     * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
     */
    public Builder setModeratorStatusValue(int value) {
      moderatorStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
     */
    public org.spin.grpc.util.ChatEntry.ModeratorStatus getModeratorStatus() {
      org.spin.grpc.util.ChatEntry.ModeratorStatus result = org.spin.grpc.util.ChatEntry.ModeratorStatus.valueOf(moderatorStatus_);
      return result == null ? org.spin.grpc.util.ChatEntry.ModeratorStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
     */
    public Builder setModeratorStatus(org.spin.grpc.util.ChatEntry.ModeratorStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      moderatorStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.data.ChatEntry.ModeratorStatus moderatorStatus = 9;</code>
     */
    public Builder clearModeratorStatus() {
      
      moderatorStatus_ = 0;
      onChanged();
      return this;
    }

    private long logDate_ ;
    /**
     * <code>int64 logDate = 10;</code>
     */
    public long getLogDate() {
      return logDate_;
    }
    /**
     * <code>int64 logDate = 10;</code>
     */
    public Builder setLogDate(long value) {
      
      logDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 logDate = 10;</code>
     */
    public Builder clearLogDate() {
      
      logDate_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ChatEntry)
  }

  // @@protoc_insertion_point(class_scope:data.ChatEntry)
  private static final org.spin.grpc.util.ChatEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.spin.grpc.util.ChatEntry();
  }

  public static org.spin.grpc.util.ChatEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatEntry>
      PARSER = new com.google.protobuf.AbstractParser<ChatEntry>() {
    public ChatEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatEntry> getParserForType() {
    return PARSER;
  }

  public org.spin.grpc.util.ChatEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

