// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: point_of_sales.proto

package org.spin.grpc.util;

public interface CreateOrderLineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.CreateOrderLineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  boolean hasClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  org.spin.grpc.util.ClientRequest getClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  org.spin.grpc.util.ClientRequestOrBuilder getClientRequestOrBuilder();

  /**
   * <code>string orderUuid = 2;</code>
   */
  java.lang.String getOrderUuid();
  /**
   * <code>string orderUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderUuidBytes();

  /**
   * <code>string productUuid = 3;</code>
   */
  java.lang.String getProductUuid();
  /**
   * <code>string productUuid = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductUuidBytes();

  /**
   * <code>string chargeUuid = 4;</code>
   */
  java.lang.String getChargeUuid();
  /**
   * <code>string chargeUuid = 4;</code>
   */
  com.google.protobuf.ByteString
      getChargeUuidBytes();

  /**
   * <code>string description = 5;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.data.Decimal quantity = 6;</code>
   */
  boolean hasQuantity();
  /**
   * <code>.data.Decimal quantity = 6;</code>
   */
  org.spin.grpc.util.Decimal getQuantity();
  /**
   * <code>.data.Decimal quantity = 6;</code>
   */
  org.spin.grpc.util.DecimalOrBuilder getQuantityOrBuilder();

  /**
   * <code>.data.Decimal price = 7;</code>
   */
  boolean hasPrice();
  /**
   * <code>.data.Decimal price = 7;</code>
   */
  org.spin.grpc.util.Decimal getPrice();
  /**
   * <code>.data.Decimal price = 7;</code>
   */
  org.spin.grpc.util.DecimalOrBuilder getPriceOrBuilder();

  /**
   * <code>.data.Decimal discountRate = 8;</code>
   */
  boolean hasDiscountRate();
  /**
   * <code>.data.Decimal discountRate = 8;</code>
   */
  org.spin.grpc.util.Decimal getDiscountRate();
  /**
   * <code>.data.Decimal discountRate = 8;</code>
   */
  org.spin.grpc.util.DecimalOrBuilder getDiscountRateOrBuilder();

  /**
   * <code>string warehouseUuid = 9;</code>
   */
  java.lang.String getWarehouseUuid();
  /**
   * <code>string warehouseUuid = 9;</code>
   */
  com.google.protobuf.ByteString
      getWarehouseUuidBytes();
}
