// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package org.spin.grpc.util;

public interface GetResourceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.GetResourceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  boolean hasClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  org.spin.grpc.util.ClientRequest getClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  org.spin.grpc.util.ClientRequestOrBuilder getClientRequestOrBuilder();

  /**
   * <code>string resourceUuid = 2;</code>
   */
  java.lang.String getResourceUuid();
  /**
   * <code>string resourceUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourceUuidBytes();
}
