// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package org.spin.grpc.util;

public interface GetReportOutputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.GetReportOutputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string printFormatUuid = 1;</code>
   */
  java.lang.String getPrintFormatUuid();
  /**
   * <code>string printFormatUuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrintFormatUuidBytes();

  /**
   * <code>string reportViewUuid = 2;</code>
   */
  java.lang.String getReportViewUuid();
  /**
   * <code>string reportViewUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getReportViewUuidBytes();

  /**
   * <code>bool isSummary = 3;</code>
   */
  boolean getIsSummary();

  /**
   * <code>string reportName = 5;</code>
   */
  java.lang.String getReportName();
  /**
   * <code>string reportName = 5;</code>
   */
  com.google.protobuf.ByteString
      getReportNameBytes();

  /**
   * <code>string reportType = 6;</code>
   */
  java.lang.String getReportType();
  /**
   * <code>string reportType = 6;</code>
   */
  com.google.protobuf.ByteString
      getReportTypeBytes();

  /**
   * <code>.data.ClientRequest clientRequest = 7;</code>
   */
  boolean hasClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 7;</code>
   */
  org.spin.grpc.util.ClientRequest getClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 7;</code>
   */
  org.spin.grpc.util.ClientRequestOrBuilder getClientRequestOrBuilder();

  /**
   * <pre>
   * Query
   * </pre>
   *
   * <code>.data.Criteria criteria = 8;</code>
   */
  boolean hasCriteria();
  /**
   * <pre>
   * Query
   * </pre>
   *
   * <code>.data.Criteria criteria = 8;</code>
   */
  org.spin.grpc.util.Criteria getCriteria();
  /**
   * <pre>
   * Query
   * </pre>
   *
   * <code>.data.Criteria criteria = 8;</code>
   */
  org.spin.grpc.util.CriteriaOrBuilder getCriteriaOrBuilder();
}
