// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: point_of_sales.proto

package org.spin.grpc.util;

/**
 * <pre>
 *	List Product Price Response
 * </pre>
 *
 * Protobuf type {@code data.ListProductPriceResponse}
 */
public  final class ListProductPriceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ListProductPriceResponse)
    ListProductPriceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListProductPriceResponse.newBuilder() to construct.
  private ListProductPriceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListProductPriceResponse() {
    recordCount_ = 0L;
    productPrices_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListProductPriceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            recordCount_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              productPrices_ = new java.util.ArrayList<org.spin.grpc.util.ProductPrice>();
              mutable_bitField0_ |= 0x00000002;
            }
            productPrices_.add(
                input.readMessage(org.spin.grpc.util.ProductPrice.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nextPageToken_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        productPrices_ = java.util.Collections.unmodifiableList(productPrices_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.spin.grpc.util.ADempierePOS.internal_static_data_ListProductPriceResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.spin.grpc.util.ADempierePOS.internal_static_data_ListProductPriceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.spin.grpc.util.ListProductPriceResponse.class, org.spin.grpc.util.ListProductPriceResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RECORDCOUNT_FIELD_NUMBER = 1;
  private long recordCount_;
  /**
   * <code>int64 recordCount = 1;</code>
   */
  public long getRecordCount() {
    return recordCount_;
  }

  public static final int PRODUCTPRICES_FIELD_NUMBER = 2;
  private java.util.List<org.spin.grpc.util.ProductPrice> productPrices_;
  /**
   * <code>repeated .data.ProductPrice productPrices = 2;</code>
   */
  public java.util.List<org.spin.grpc.util.ProductPrice> getProductPricesList() {
    return productPrices_;
  }
  /**
   * <code>repeated .data.ProductPrice productPrices = 2;</code>
   */
  public java.util.List<? extends org.spin.grpc.util.ProductPriceOrBuilder> 
      getProductPricesOrBuilderList() {
    return productPrices_;
  }
  /**
   * <code>repeated .data.ProductPrice productPrices = 2;</code>
   */
  public int getProductPricesCount() {
    return productPrices_.size();
  }
  /**
   * <code>repeated .data.ProductPrice productPrices = 2;</code>
   */
  public org.spin.grpc.util.ProductPrice getProductPrices(int index) {
    return productPrices_.get(index);
  }
  /**
   * <code>repeated .data.ProductPrice productPrices = 2;</code>
   */
  public org.spin.grpc.util.ProductPriceOrBuilder getProductPricesOrBuilder(
      int index) {
    return productPrices_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 3;
  private volatile java.lang.Object nextPageToken_;
  /**
   * <code>string next_page_token = 3;</code>
   */
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <code>string next_page_token = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (recordCount_ != 0L) {
      output.writeInt64(1, recordCount_);
    }
    for (int i = 0; i < productPrices_.size(); i++) {
      output.writeMessage(2, productPrices_.get(i));
    }
    if (!getNextPageTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nextPageToken_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (recordCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, recordCount_);
    }
    for (int i = 0; i < productPrices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, productPrices_.get(i));
    }
    if (!getNextPageTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nextPageToken_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.spin.grpc.util.ListProductPriceResponse)) {
      return super.equals(obj);
    }
    org.spin.grpc.util.ListProductPriceResponse other = (org.spin.grpc.util.ListProductPriceResponse) obj;

    boolean result = true;
    result = result && (getRecordCount()
        == other.getRecordCount());
    result = result && getProductPricesList()
        .equals(other.getProductPricesList());
    result = result && getNextPageToken()
        .equals(other.getNextPageToken());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORDCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRecordCount());
    if (getProductPricesCount() > 0) {
      hash = (37 * hash) + PRODUCTPRICES_FIELD_NUMBER;
      hash = (53 * hash) + getProductPricesList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ListProductPriceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.spin.grpc.util.ListProductPriceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *	List Product Price Response
   * </pre>
   *
   * Protobuf type {@code data.ListProductPriceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ListProductPriceResponse)
      org.spin.grpc.util.ListProductPriceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.spin.grpc.util.ADempierePOS.internal_static_data_ListProductPriceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.spin.grpc.util.ADempierePOS.internal_static_data_ListProductPriceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.spin.grpc.util.ListProductPriceResponse.class, org.spin.grpc.util.ListProductPriceResponse.Builder.class);
    }

    // Construct using org.spin.grpc.util.ListProductPriceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductPricesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      recordCount_ = 0L;

      if (productPricesBuilder_ == null) {
        productPrices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        productPricesBuilder_.clear();
      }
      nextPageToken_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.spin.grpc.util.ADempierePOS.internal_static_data_ListProductPriceResponse_descriptor;
    }

    public org.spin.grpc.util.ListProductPriceResponse getDefaultInstanceForType() {
      return org.spin.grpc.util.ListProductPriceResponse.getDefaultInstance();
    }

    public org.spin.grpc.util.ListProductPriceResponse build() {
      org.spin.grpc.util.ListProductPriceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.spin.grpc.util.ListProductPriceResponse buildPartial() {
      org.spin.grpc.util.ListProductPriceResponse result = new org.spin.grpc.util.ListProductPriceResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.recordCount_ = recordCount_;
      if (productPricesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          productPrices_ = java.util.Collections.unmodifiableList(productPrices_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.productPrices_ = productPrices_;
      } else {
        result.productPrices_ = productPricesBuilder_.build();
      }
      result.nextPageToken_ = nextPageToken_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.spin.grpc.util.ListProductPriceResponse) {
        return mergeFrom((org.spin.grpc.util.ListProductPriceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.spin.grpc.util.ListProductPriceResponse other) {
      if (other == org.spin.grpc.util.ListProductPriceResponse.getDefaultInstance()) return this;
      if (other.getRecordCount() != 0L) {
        setRecordCount(other.getRecordCount());
      }
      if (productPricesBuilder_ == null) {
        if (!other.productPrices_.isEmpty()) {
          if (productPrices_.isEmpty()) {
            productPrices_ = other.productPrices_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureProductPricesIsMutable();
            productPrices_.addAll(other.productPrices_);
          }
          onChanged();
        }
      } else {
        if (!other.productPrices_.isEmpty()) {
          if (productPricesBuilder_.isEmpty()) {
            productPricesBuilder_.dispose();
            productPricesBuilder_ = null;
            productPrices_ = other.productPrices_;
            bitField0_ = (bitField0_ & ~0x00000002);
            productPricesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductPricesFieldBuilder() : null;
          } else {
            productPricesBuilder_.addAllMessages(other.productPrices_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.spin.grpc.util.ListProductPriceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.spin.grpc.util.ListProductPriceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long recordCount_ ;
    /**
     * <code>int64 recordCount = 1;</code>
     */
    public long getRecordCount() {
      return recordCount_;
    }
    /**
     * <code>int64 recordCount = 1;</code>
     */
    public Builder setRecordCount(long value) {
      
      recordCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 recordCount = 1;</code>
     */
    public Builder clearRecordCount() {
      
      recordCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.spin.grpc.util.ProductPrice> productPrices_ =
      java.util.Collections.emptyList();
    private void ensureProductPricesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        productPrices_ = new java.util.ArrayList<org.spin.grpc.util.ProductPrice>(productPrices_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.spin.grpc.util.ProductPrice, org.spin.grpc.util.ProductPrice.Builder, org.spin.grpc.util.ProductPriceOrBuilder> productPricesBuilder_;

    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public java.util.List<org.spin.grpc.util.ProductPrice> getProductPricesList() {
      if (productPricesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(productPrices_);
      } else {
        return productPricesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public int getProductPricesCount() {
      if (productPricesBuilder_ == null) {
        return productPrices_.size();
      } else {
        return productPricesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public org.spin.grpc.util.ProductPrice getProductPrices(int index) {
      if (productPricesBuilder_ == null) {
        return productPrices_.get(index);
      } else {
        return productPricesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder setProductPrices(
        int index, org.spin.grpc.util.ProductPrice value) {
      if (productPricesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductPricesIsMutable();
        productPrices_.set(index, value);
        onChanged();
      } else {
        productPricesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder setProductPrices(
        int index, org.spin.grpc.util.ProductPrice.Builder builderForValue) {
      if (productPricesBuilder_ == null) {
        ensureProductPricesIsMutable();
        productPrices_.set(index, builderForValue.build());
        onChanged();
      } else {
        productPricesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder addProductPrices(org.spin.grpc.util.ProductPrice value) {
      if (productPricesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductPricesIsMutable();
        productPrices_.add(value);
        onChanged();
      } else {
        productPricesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder addProductPrices(
        int index, org.spin.grpc.util.ProductPrice value) {
      if (productPricesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductPricesIsMutable();
        productPrices_.add(index, value);
        onChanged();
      } else {
        productPricesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder addProductPrices(
        org.spin.grpc.util.ProductPrice.Builder builderForValue) {
      if (productPricesBuilder_ == null) {
        ensureProductPricesIsMutable();
        productPrices_.add(builderForValue.build());
        onChanged();
      } else {
        productPricesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder addProductPrices(
        int index, org.spin.grpc.util.ProductPrice.Builder builderForValue) {
      if (productPricesBuilder_ == null) {
        ensureProductPricesIsMutable();
        productPrices_.add(index, builderForValue.build());
        onChanged();
      } else {
        productPricesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder addAllProductPrices(
        java.lang.Iterable<? extends org.spin.grpc.util.ProductPrice> values) {
      if (productPricesBuilder_ == null) {
        ensureProductPricesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productPrices_);
        onChanged();
      } else {
        productPricesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder clearProductPrices() {
      if (productPricesBuilder_ == null) {
        productPrices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        productPricesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public Builder removeProductPrices(int index) {
      if (productPricesBuilder_ == null) {
        ensureProductPricesIsMutable();
        productPrices_.remove(index);
        onChanged();
      } else {
        productPricesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public org.spin.grpc.util.ProductPrice.Builder getProductPricesBuilder(
        int index) {
      return getProductPricesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public org.spin.grpc.util.ProductPriceOrBuilder getProductPricesOrBuilder(
        int index) {
      if (productPricesBuilder_ == null) {
        return productPrices_.get(index);  } else {
        return productPricesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public java.util.List<? extends org.spin.grpc.util.ProductPriceOrBuilder> 
         getProductPricesOrBuilderList() {
      if (productPricesBuilder_ != null) {
        return productPricesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(productPrices_);
      }
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public org.spin.grpc.util.ProductPrice.Builder addProductPricesBuilder() {
      return getProductPricesFieldBuilder().addBuilder(
          org.spin.grpc.util.ProductPrice.getDefaultInstance());
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public org.spin.grpc.util.ProductPrice.Builder addProductPricesBuilder(
        int index) {
      return getProductPricesFieldBuilder().addBuilder(
          index, org.spin.grpc.util.ProductPrice.getDefaultInstance());
    }
    /**
     * <code>repeated .data.ProductPrice productPrices = 2;</code>
     */
    public java.util.List<org.spin.grpc.util.ProductPrice.Builder> 
         getProductPricesBuilderList() {
      return getProductPricesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.spin.grpc.util.ProductPrice, org.spin.grpc.util.ProductPrice.Builder, org.spin.grpc.util.ProductPriceOrBuilder> 
        getProductPricesFieldBuilder() {
      if (productPricesBuilder_ == null) {
        productPricesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.spin.grpc.util.ProductPrice, org.spin.grpc.util.ProductPrice.Builder, org.spin.grpc.util.ProductPriceOrBuilder>(
                productPrices_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        productPrices_ = null;
      }
      return productPricesBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <code>string next_page_token = 3;</code>
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string next_page_token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string next_page_token = 3;</code>
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string next_page_token = 3;</code>
     */
    public Builder clearNextPageToken() {
      
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      onChanged();
      return this;
    }
    /**
     * <code>string next_page_token = 3;</code>
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ListProductPriceResponse)
  }

  // @@protoc_insertion_point(class_scope:data.ListProductPriceResponse)
  private static final org.spin.grpc.util.ListProductPriceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.spin.grpc.util.ListProductPriceResponse();
  }

  public static org.spin.grpc.util.ListProductPriceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListProductPriceResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListProductPriceResponse>() {
    public ListProductPriceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListProductPriceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListProductPriceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListProductPriceResponse> getParserForType() {
    return PARSER;
  }

  public org.spin.grpc.util.ListProductPriceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

