// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package org.spin.grpc.util;

public interface ListRecordChatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.ListRecordChatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 recordCount = 1;</code>
   */
  long getRecordCount();

  /**
   * <code>repeated .data.RecordChat recordChats = 2;</code>
   */
  java.util.List<org.spin.grpc.util.RecordChat> 
      getRecordChatsList();
  /**
   * <code>repeated .data.RecordChat recordChats = 2;</code>
   */
  org.spin.grpc.util.RecordChat getRecordChats(int index);
  /**
   * <code>repeated .data.RecordChat recordChats = 2;</code>
   */
  int getRecordChatsCount();
  /**
   * <code>repeated .data.RecordChat recordChats = 2;</code>
   */
  java.util.List<? extends org.spin.grpc.util.RecordChatOrBuilder> 
      getRecordChatsOrBuilderList();
  /**
   * <code>repeated .data.RecordChat recordChats = 2;</code>
   */
  org.spin.grpc.util.RecordChatOrBuilder getRecordChatsOrBuilder(
      int index);

  /**
   * <code>string next_page_token = 3;</code>
   */
  java.lang.String getNextPageToken();
  /**
   * <code>string next_page_token = 3;</code>
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
