// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: point_of_sales.proto

package org.spin.grpc.util;

public interface PointOfSalesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.PointOfSalesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  boolean hasClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  org.spin.grpc.util.ClientRequest getClientRequest();
  /**
   * <code>.data.ClientRequest clientRequest = 1;</code>
   */
  org.spin.grpc.util.ClientRequestOrBuilder getClientRequestOrBuilder();

  /**
   * <code>string pointOfSalesUuid = 2;</code>
   */
  java.lang.String getPointOfSalesUuid();
  /**
   * <code>string pointOfSalesUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getPointOfSalesUuidBytes();
}
