// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_data_type.proto

package org.spin.grpc.util;

/**
 * <pre>
 *	Used for get output from report / BusinessProcess like PDF, HTML another result for show to end user
 * </pre>
 *
 * Protobuf type {@code data.ReportOutput}
 */
public  final class ReportOutput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ReportOutput)
    ReportOutputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportOutput.newBuilder() to construct.
  private ReportOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportOutput() {
    uuid_ = "";
    name_ = "";
    description_ = "";
    fileName_ = "";
    output_ = "";
    mimeType_ = "";
    dataCols_ = 0L;
    dataRows_ = 0L;
    headerName_ = "";
    footerName_ = "";
    printFormatUuid_ = "";
    reportViewUuid_ = "";
    tableName_ = "";
    outputStream_ = com.google.protobuf.ByteString.EMPTY;
    reportType_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportOutput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            output_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            mimeType_ = s;
            break;
          }
          case 56: {

            dataCols_ = input.readInt64();
            break;
          }
          case 64: {

            dataRows_ = input.readInt64();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            headerName_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            footerName_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            printFormatUuid_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            reportViewUuid_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 114: {

            outputStream_ = input.readBytes();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            reportType_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.spin.grpc.util.ADempiereBase.internal_static_data_ReportOutput_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.spin.grpc.util.ADempiereBase.internal_static_data_ReportOutput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.spin.grpc.util.ReportOutput.class, org.spin.grpc.util.ReportOutput.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uuid_;
  /**
   * <code>string uuid = 1;</code>
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILENAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object fileName_;
  /**
   * <code>string fileName = 4;</code>
   */
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUT_FIELD_NUMBER = 5;
  private volatile java.lang.Object output_;
  /**
   * <code>string output = 5;</code>
   */
  public java.lang.String getOutput() {
    java.lang.Object ref = output_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      output_ = s;
      return s;
    }
  }
  /**
   * <code>string output = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOutputBytes() {
    java.lang.Object ref = output_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      output_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIMETYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object mimeType_;
  /**
   * <code>string mimeType = 6;</code>
   */
  public java.lang.String getMimeType() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mimeType_ = s;
      return s;
    }
  }
  /**
   * <code>string mimeType = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mimeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATACOLS_FIELD_NUMBER = 7;
  private long dataCols_;
  /**
   * <code>int64 dataCols = 7;</code>
   */
  public long getDataCols() {
    return dataCols_;
  }

  public static final int DATAROWS_FIELD_NUMBER = 8;
  private long dataRows_;
  /**
   * <code>int64 dataRows = 8;</code>
   */
  public long getDataRows() {
    return dataRows_;
  }

  public static final int HEADERNAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object headerName_;
  /**
   * <code>string headerName = 9;</code>
   */
  public java.lang.String getHeaderName() {
    java.lang.Object ref = headerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      headerName_ = s;
      return s;
    }
  }
  /**
   * <code>string headerName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getHeaderNameBytes() {
    java.lang.Object ref = headerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      headerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOOTERNAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object footerName_;
  /**
   * <code>string footerName = 10;</code>
   */
  public java.lang.String getFooterName() {
    java.lang.Object ref = footerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      footerName_ = s;
      return s;
    }
  }
  /**
   * <code>string footerName = 10;</code>
   */
  public com.google.protobuf.ByteString
      getFooterNameBytes() {
    java.lang.Object ref = footerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      footerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRINTFORMATUUID_FIELD_NUMBER = 11;
  private volatile java.lang.Object printFormatUuid_;
  /**
   * <code>string printFormatUuid = 11;</code>
   */
  public java.lang.String getPrintFormatUuid() {
    java.lang.Object ref = printFormatUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      printFormatUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string printFormatUuid = 11;</code>
   */
  public com.google.protobuf.ByteString
      getPrintFormatUuidBytes() {
    java.lang.Object ref = printFormatUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      printFormatUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORTVIEWUUID_FIELD_NUMBER = 12;
  private volatile java.lang.Object reportViewUuid_;
  /**
   * <code>string reportViewUuid = 12;</code>
   */
  public java.lang.String getReportViewUuid() {
    java.lang.Object ref = reportViewUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportViewUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string reportViewUuid = 12;</code>
   */
  public com.google.protobuf.ByteString
      getReportViewUuidBytes() {
    java.lang.Object ref = reportViewUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportViewUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAME_FIELD_NUMBER = 13;
  private volatile java.lang.Object tableName_;
  /**
   * <code>string tableName = 13;</code>
   */
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string tableName = 13;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUTSTREAM_FIELD_NUMBER = 14;
  private com.google.protobuf.ByteString outputStream_;
  /**
   * <code>bytes outputStream = 14;</code>
   */
  public com.google.protobuf.ByteString getOutputStream() {
    return outputStream_;
  }

  public static final int REPORTTYPE_FIELD_NUMBER = 15;
  private volatile java.lang.Object reportType_;
  /**
   * <pre>
   *	Output Type
   * </pre>
   *
   * <code>string reportType = 15;</code>
   */
  public java.lang.String getReportType() {
    java.lang.Object ref = reportType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *	Output Type
   * </pre>
   *
   * <code>string reportType = 15;</code>
   */
  public com.google.protobuf.ByteString
      getReportTypeBytes() {
    java.lang.Object ref = reportType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileName_);
    }
    if (!getOutputBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, output_);
    }
    if (!getMimeTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mimeType_);
    }
    if (dataCols_ != 0L) {
      output.writeInt64(7, dataCols_);
    }
    if (dataRows_ != 0L) {
      output.writeInt64(8, dataRows_);
    }
    if (!getHeaderNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, headerName_);
    }
    if (!getFooterNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, footerName_);
    }
    if (!getPrintFormatUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, printFormatUuid_);
    }
    if (!getReportViewUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, reportViewUuid_);
    }
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, tableName_);
    }
    if (!outputStream_.isEmpty()) {
      output.writeBytes(14, outputStream_);
    }
    if (!getReportTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, reportType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileName_);
    }
    if (!getOutputBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, output_);
    }
    if (!getMimeTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mimeType_);
    }
    if (dataCols_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, dataCols_);
    }
    if (dataRows_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, dataRows_);
    }
    if (!getHeaderNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, headerName_);
    }
    if (!getFooterNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, footerName_);
    }
    if (!getPrintFormatUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, printFormatUuid_);
    }
    if (!getReportViewUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, reportViewUuid_);
    }
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, tableName_);
    }
    if (!outputStream_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, outputStream_);
    }
    if (!getReportTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, reportType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.spin.grpc.util.ReportOutput)) {
      return super.equals(obj);
    }
    org.spin.grpc.util.ReportOutput other = (org.spin.grpc.util.ReportOutput) obj;

    boolean result = true;
    result = result && getUuid()
        .equals(other.getUuid());
    result = result && getName()
        .equals(other.getName());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getFileName()
        .equals(other.getFileName());
    result = result && getOutput()
        .equals(other.getOutput());
    result = result && getMimeType()
        .equals(other.getMimeType());
    result = result && (getDataCols()
        == other.getDataCols());
    result = result && (getDataRows()
        == other.getDataRows());
    result = result && getHeaderName()
        .equals(other.getHeaderName());
    result = result && getFooterName()
        .equals(other.getFooterName());
    result = result && getPrintFormatUuid()
        .equals(other.getPrintFormatUuid());
    result = result && getReportViewUuid()
        .equals(other.getReportViewUuid());
    result = result && getTableName()
        .equals(other.getTableName());
    result = result && getOutputStream()
        .equals(other.getOutputStream());
    result = result && getReportType()
        .equals(other.getReportType());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
    hash = (53 * hash) + getOutput().hashCode();
    hash = (37 * hash) + MIMETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMimeType().hashCode();
    hash = (37 * hash) + DATACOLS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDataCols());
    hash = (37 * hash) + DATAROWS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDataRows());
    hash = (37 * hash) + HEADERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHeaderName().hashCode();
    hash = (37 * hash) + FOOTERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFooterName().hashCode();
    hash = (37 * hash) + PRINTFORMATUUID_FIELD_NUMBER;
    hash = (53 * hash) + getPrintFormatUuid().hashCode();
    hash = (37 * hash) + REPORTVIEWUUID_FIELD_NUMBER;
    hash = (53 * hash) + getReportViewUuid().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + OUTPUTSTREAM_FIELD_NUMBER;
    hash = (53 * hash) + getOutputStream().hashCode();
    hash = (37 * hash) + REPORTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getReportType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.spin.grpc.util.ReportOutput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.spin.grpc.util.ReportOutput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ReportOutput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.spin.grpc.util.ReportOutput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.spin.grpc.util.ReportOutput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *	Used for get output from report / BusinessProcess like PDF, HTML another result for show to end user
   * </pre>
   *
   * Protobuf type {@code data.ReportOutput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ReportOutput)
      org.spin.grpc.util.ReportOutputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.spin.grpc.util.ADempiereBase.internal_static_data_ReportOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.spin.grpc.util.ADempiereBase.internal_static_data_ReportOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.spin.grpc.util.ReportOutput.class, org.spin.grpc.util.ReportOutput.Builder.class);
    }

    // Construct using org.spin.grpc.util.ReportOutput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uuid_ = "";

      name_ = "";

      description_ = "";

      fileName_ = "";

      output_ = "";

      mimeType_ = "";

      dataCols_ = 0L;

      dataRows_ = 0L;

      headerName_ = "";

      footerName_ = "";

      printFormatUuid_ = "";

      reportViewUuid_ = "";

      tableName_ = "";

      outputStream_ = com.google.protobuf.ByteString.EMPTY;

      reportType_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.spin.grpc.util.ADempiereBase.internal_static_data_ReportOutput_descriptor;
    }

    public org.spin.grpc.util.ReportOutput getDefaultInstanceForType() {
      return org.spin.grpc.util.ReportOutput.getDefaultInstance();
    }

    public org.spin.grpc.util.ReportOutput build() {
      org.spin.grpc.util.ReportOutput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.spin.grpc.util.ReportOutput buildPartial() {
      org.spin.grpc.util.ReportOutput result = new org.spin.grpc.util.ReportOutput(this);
      result.uuid_ = uuid_;
      result.name_ = name_;
      result.description_ = description_;
      result.fileName_ = fileName_;
      result.output_ = output_;
      result.mimeType_ = mimeType_;
      result.dataCols_ = dataCols_;
      result.dataRows_ = dataRows_;
      result.headerName_ = headerName_;
      result.footerName_ = footerName_;
      result.printFormatUuid_ = printFormatUuid_;
      result.reportViewUuid_ = reportViewUuid_;
      result.tableName_ = tableName_;
      result.outputStream_ = outputStream_;
      result.reportType_ = reportType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.spin.grpc.util.ReportOutput) {
        return mergeFrom((org.spin.grpc.util.ReportOutput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.spin.grpc.util.ReportOutput other) {
      if (other == org.spin.grpc.util.ReportOutput.getDefaultInstance()) return this;
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (!other.getOutput().isEmpty()) {
        output_ = other.output_;
        onChanged();
      }
      if (!other.getMimeType().isEmpty()) {
        mimeType_ = other.mimeType_;
        onChanged();
      }
      if (other.getDataCols() != 0L) {
        setDataCols(other.getDataCols());
      }
      if (other.getDataRows() != 0L) {
        setDataRows(other.getDataRows());
      }
      if (!other.getHeaderName().isEmpty()) {
        headerName_ = other.headerName_;
        onChanged();
      }
      if (!other.getFooterName().isEmpty()) {
        footerName_ = other.footerName_;
        onChanged();
      }
      if (!other.getPrintFormatUuid().isEmpty()) {
        printFormatUuid_ = other.printFormatUuid_;
        onChanged();
      }
      if (!other.getReportViewUuid().isEmpty()) {
        reportViewUuid_ = other.reportViewUuid_;
        onChanged();
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (other.getOutputStream() != com.google.protobuf.ByteString.EMPTY) {
        setOutputStream(other.getOutputStream());
      }
      if (!other.getReportType().isEmpty()) {
        reportType_ = other.reportType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.spin.grpc.util.ReportOutput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.spin.grpc.util.ReportOutput) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 4;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 4;</code>
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 4;</code>
     */
    public Builder clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 4;</code>
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object output_ = "";
    /**
     * <code>string output = 5;</code>
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string output = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string output = 5;</code>
     */
    public Builder setOutput(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      output_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string output = 5;</code>
     */
    public Builder clearOutput() {
      
      output_ = getDefaultInstance().getOutput();
      onChanged();
      return this;
    }
    /**
     * <code>string output = 5;</code>
     */
    public Builder setOutputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      output_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mimeType_ = "";
    /**
     * <code>string mimeType = 6;</code>
     */
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mimeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mimeType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mimeType = 6;</code>
     */
    public Builder setMimeType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mimeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mimeType = 6;</code>
     */
    public Builder clearMimeType() {
      
      mimeType_ = getDefaultInstance().getMimeType();
      onChanged();
      return this;
    }
    /**
     * <code>string mimeType = 6;</code>
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mimeType_ = value;
      onChanged();
      return this;
    }

    private long dataCols_ ;
    /**
     * <code>int64 dataCols = 7;</code>
     */
    public long getDataCols() {
      return dataCols_;
    }
    /**
     * <code>int64 dataCols = 7;</code>
     */
    public Builder setDataCols(long value) {
      
      dataCols_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 dataCols = 7;</code>
     */
    public Builder clearDataCols() {
      
      dataCols_ = 0L;
      onChanged();
      return this;
    }

    private long dataRows_ ;
    /**
     * <code>int64 dataRows = 8;</code>
     */
    public long getDataRows() {
      return dataRows_;
    }
    /**
     * <code>int64 dataRows = 8;</code>
     */
    public Builder setDataRows(long value) {
      
      dataRows_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 dataRows = 8;</code>
     */
    public Builder clearDataRows() {
      
      dataRows_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object headerName_ = "";
    /**
     * <code>string headerName = 9;</code>
     */
    public java.lang.String getHeaderName() {
      java.lang.Object ref = headerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string headerName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderNameBytes() {
      java.lang.Object ref = headerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string headerName = 9;</code>
     */
    public Builder setHeaderName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      headerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string headerName = 9;</code>
     */
    public Builder clearHeaderName() {
      
      headerName_ = getDefaultInstance().getHeaderName();
      onChanged();
      return this;
    }
    /**
     * <code>string headerName = 9;</code>
     */
    public Builder setHeaderNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      headerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object footerName_ = "";
    /**
     * <code>string footerName = 10;</code>
     */
    public java.lang.String getFooterName() {
      java.lang.Object ref = footerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        footerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string footerName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFooterNameBytes() {
      java.lang.Object ref = footerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        footerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string footerName = 10;</code>
     */
    public Builder setFooterName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      footerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string footerName = 10;</code>
     */
    public Builder clearFooterName() {
      
      footerName_ = getDefaultInstance().getFooterName();
      onChanged();
      return this;
    }
    /**
     * <code>string footerName = 10;</code>
     */
    public Builder setFooterNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      footerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object printFormatUuid_ = "";
    /**
     * <code>string printFormatUuid = 11;</code>
     */
    public java.lang.String getPrintFormatUuid() {
      java.lang.Object ref = printFormatUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        printFormatUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string printFormatUuid = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPrintFormatUuidBytes() {
      java.lang.Object ref = printFormatUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        printFormatUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string printFormatUuid = 11;</code>
     */
    public Builder setPrintFormatUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      printFormatUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string printFormatUuid = 11;</code>
     */
    public Builder clearPrintFormatUuid() {
      
      printFormatUuid_ = getDefaultInstance().getPrintFormatUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string printFormatUuid = 11;</code>
     */
    public Builder setPrintFormatUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      printFormatUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object reportViewUuid_ = "";
    /**
     * <code>string reportViewUuid = 12;</code>
     */
    public java.lang.String getReportViewUuid() {
      java.lang.Object ref = reportViewUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportViewUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reportViewUuid = 12;</code>
     */
    public com.google.protobuf.ByteString
        getReportViewUuidBytes() {
      java.lang.Object ref = reportViewUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportViewUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reportViewUuid = 12;</code>
     */
    public Builder setReportViewUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reportViewUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reportViewUuid = 12;</code>
     */
    public Builder clearReportViewUuid() {
      
      reportViewUuid_ = getDefaultInstance().getReportViewUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string reportViewUuid = 12;</code>
     */
    public Builder setReportViewUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reportViewUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <code>string tableName = 13;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableName = 13;</code>
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 13;</code>
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 13;</code>
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString outputStream_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes outputStream = 14;</code>
     */
    public com.google.protobuf.ByteString getOutputStream() {
      return outputStream_;
    }
    /**
     * <code>bytes outputStream = 14;</code>
     */
    public Builder setOutputStream(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outputStream_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes outputStream = 14;</code>
     */
    public Builder clearOutputStream() {
      
      outputStream_ = getDefaultInstance().getOutputStream();
      onChanged();
      return this;
    }

    private java.lang.Object reportType_ = "";
    /**
     * <pre>
     *	Output Type
     * </pre>
     *
     * <code>string reportType = 15;</code>
     */
    public java.lang.String getReportType() {
      java.lang.Object ref = reportType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *	Output Type
     * </pre>
     *
     * <code>string reportType = 15;</code>
     */
    public com.google.protobuf.ByteString
        getReportTypeBytes() {
      java.lang.Object ref = reportType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *	Output Type
     * </pre>
     *
     * <code>string reportType = 15;</code>
     */
    public Builder setReportType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reportType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *	Output Type
     * </pre>
     *
     * <code>string reportType = 15;</code>
     */
    public Builder clearReportType() {
      
      reportType_ = getDefaultInstance().getReportType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *	Output Type
     * </pre>
     *
     * <code>string reportType = 15;</code>
     */
    public Builder setReportTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reportType_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ReportOutput)
  }

  // @@protoc_insertion_point(class_scope:data.ReportOutput)
  private static final org.spin.grpc.util.ReportOutput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.spin.grpc.util.ReportOutput();
  }

  public static org.spin.grpc.util.ReportOutput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportOutput>
      PARSER = new com.google.protobuf.AbstractParser<ReportOutput>() {
    public ReportOutput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportOutput(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportOutput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportOutput> getParserForType() {
    return PARSER;
  }

  public org.spin.grpc.util.ReportOutput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

