// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dictionary.proto

package org.spin.grpc.util;

public interface ValidationRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dictionary.ValidationRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string validationRuleUuid = 1;</code>
   */
  java.lang.String getValidationRuleUuid();
  /**
   * <code>string validationRuleUuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getValidationRuleUuidBytes();

  /**
   * <code>string validationCode = 2;</code>
   */
  java.lang.String getValidationCode();
  /**
   * <code>string validationCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getValidationCodeBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 4;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string type = 5;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
